apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailslurper.fullname" . }}
  labels:
    {{- include "mailslurper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4436
      protocol: TCP
  selector:
    {{- include "mailslurper.selectorLabels" . | nindent 4 }}
